# Generated by Django 4.0.3 on 2022-04-01 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveFromDate', models.DateField()),
                ('leaveToDate', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('modifiedBy', models.CharField(max_length=255, null=True)),
                ('modifiedDate', models.DateField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
