# Generated by Django 4.0.3 on 2022-03-27 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_alter_employee_address_alter_employee_dateofjoining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='isActive',
        ),
        migrations.AddField(
            model_name='employee',
            name='createdBy',
            field=models.CharField(default='2022-03-25', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='createdDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='modifiedBy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='modifiedDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
