# Generated by Django 4.0.3 on 2022-03-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Designation', '0002_alter_designation_modifiedby_and_more'),
        ('Department', '0004_alter_department_modifieddate'),
        ('Employee', '0012_rename_status_employee_isactive_employee_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Designation.designation'),
        ),
    ]
