# Generated by Django 4.0.3 on 2022-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_alter_employee_department_alter_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='availableAnualLeave',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='employee',
            name='availableCasualLeave',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='employee',
            name='availableSickLeave',
            field=models.IntegerField(default=7),
        ),
    ]
