# Generated by Django 4.0.3 on 2022-04-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0014_employee_availableanualleave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='availableAnualLeave',
            new_name='availableAnnualLeave',
        ),
    ]
