# Generated by Django 4.0.3 on 2022-04-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_rename_availableanualleave_employee_availableannualleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='createdBy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='createdDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='modifiedBy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='modifiedDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
