# Generated by Django 4.0.3 on 2022-04-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0016_role_createdby_role_createddate_role_modifiedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergencyContact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='Male', max_length=255),
        ),
    ]
