# Generated by Django 4.0.3 on 2022-04-15 04:43

import Employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0017_employee_emergencycontact_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Employee.models.nameFile),
        ),
    ]
