# Generated by Django 4.0.3 on 2022-04-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timesheet', '0002_alter_timesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
