# Generated by Django 4.0.3 on 2022-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeType', models.CharField(max_length=255)),
                ('noticeTitle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('noticeDate', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('modifiedBy', models.CharField(max_length=255)),
                ('modifiedDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
