# Generated by Django 4.0.3 on 2022-03-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeboard',
            old_name='status',
            new_name='isShow',
        ),
    ]
