# Generated by Django 4.0.3 on 2022-04-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeBoard', '0002_rename_status_noticeboard_isshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='noticeDate',
            field=models.DateField(null=True),
        ),
    ]
