# Generated by Django 4.0.3 on 2022-04-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designation', '0002_alter_designation_modifiedby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='deesignationName',
            new_name='designationName',
        ),
    ]
