# Generated by Django 4.0.3 on 2022-03-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.CharField(max_length=255)),
                ('modifiedBy', models.CharField(max_length=255)),
                ('modifiedDate', models.CharField(max_length=255)),
            ],
        ),
    ]
