# Generated by Django 4.0.3 on 2022-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_alter_department_modifiedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='modifiedDate',
            field=models.DateField(auto_now=True),
        ),
    ]
